default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crud_development
  
test:
  <<: *default
  database: crud_test


production:
  <<: *default
  database: crud_production
  username: crud
  password: <%= ENV["CRUD_DATABASE_PASSWORD"] %>
